### ISSUE TITLE
[Feature Request] Fishing rod enchants make bar larger

### ISSUE THREAD

**Issue by 3ncanis** [BrownBear85/stardewfishing#3]
In stardew, the better your fishing rod the larger your bar is to make fishing easier. It would be nice if Luck of the Sea or Lure made the bar larger to emulate that. Even the better fishing rods from Aquaculture making the bar larger as well since theres already integration would be amazing.

**Comment by BrownBear85** [comment]
We actually have an update currently in development which will add multiple bobber items that can be equipped with the Aquaculture tackle box, and one of these increases the bar size. I will pass this suggestion onto the mod's owner and will let you know what he says.

**Comment by goldrat1** [comment]
Mod owner here!
As far as I can tell in Stardew the only thing that affects bar size is the Cork Bobber. Fortunately we're adding that in with the Aquaculture integration in an update sometime soon :)

**Comment by 3ncanis** [comment]
Awesome sounds perfect
